### ISSUE TITLE
Union operator | used in cross_correlation plugin but not supported in python<3.10

### ISSUE THREAD

**Issue by DataGeoranger** [pastas/pastas-plugins#13]
Hello!

I was testing the crosscorrelation_seriesJ.ipynb I found out that I couldn't import the cross-correlation plugins; please see screenshot 1 below. However, the other three plugins were imported find. May I ask if I missed anything or if it might be a bug fix? Thank you very much!

Regards,

Screenshot 1
![image](https://github.com/user-attachments/assets/d2c43f77-c507-413e-8b2f-6b8cfec38e87)

Screenshot 2
![image](https://github.com/user-attachments/assets/f18b1735-9265-46ec-aeff-cb0064bb8a2f)

**Comment by martinvonk** [comment]
Hi @DataGeoranger,

This is an issue with the `|` operator in the typing library. This operator is only supported since python 3.10 (see [pep0604] (https://peps.python.org/pep-0604/)). The fault on our part is that I didn't use the `Union` type from the typing library or that we didn't specify python>=3.10 in the pyproject.toml.

**Comment by DataGeoranger** [comment]
Hi @martinvonk 
Got it. Thank you, Martin.

**Comment by dbrakenhoff** [comment]
Fixed by #14
